name: Yem
title: Yem
description: >-
    I will take you on the fabulous world of exploration. Travel, culture,
    lifestyle. Eat, Pray, Love and Coding!
logo: assets/images/logo.png
favicon: assets/images/logo.png
baseurl: ''
google_analytics: UA-xxxxxxxx-1
disqus: demowebsite
mailchimp-list: false
future: false
include:
    - _pages
permalink: '/:title/'
email: nnsang24@gmail.com
authors:
    Sang:
        name: Sang Nguyen
        display_name: Sang
        avatar: assets/images/one_avatar.jpg
        email: nnsang24@gmail.com
        web: 'https://ngocsangyem.github.io'
        twitter: 'https://twitter.com/ngocsangyem'
        description: ''
plugins:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-archives
    - jekyll-figure
    - jekyll-minifier
jekyll-archives:
    enabled:
        - categories
    layout: archive
    permalinks:
        category: '/category/:name/'
jekyll_admin:
    hidden_links:
        # - posts
        # - pages
        # - staticfiles
        - datafiles
        - configuration
paginate: 6
paginate_path: '/page:num/'
highlighter: rouge
markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true
adsense: disabled
adsense-data-ad-client: ca-pub-3412143450191416
adsense-data-ad-slot: '1363087678'
lazyimages: enabled
authorbox: disabled
sass:
    sass_dir: _sass
    style: compressed
exclude:
    - package.json
    - changelog.md
    - LICENSE.txt
    - README.md
    - Gemfile
    - Gemfile.lock
    - package-lock.json
    - node_modules
# Responsive images
responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 20 # lq
      quality: 10
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 90

  # [Optional, Default: false]
  # Rotate resized images depending on their EXIF rotation attribute. Useful for
  # working with JPGs directly from digital cameras and smartphones
  auto_rotate: false

  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: assets/images

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/images/resized/%{width}/%{basename}

  # [Optional, Default: true]
  # Whether or not to save the generated assets into the source folder.
  save_to_source: false

  # [Optional, Default: false]
  # Cache the result of {% responsive_image %} and {% responsive_image_block %} 
  # tags. See the "Caching" section of the README for more information.
  cache: true

  #/ [Optional, Default: []]
  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  extra_images:
    - assets/foo/bar.png
    - assets/bgs/*.png
    - assets/avatars/*.{jpeg,jpg}
